---
- name: Sai Trying my first Ansible Playbook
  hosts: webservers
  remote_user: ec2-user
  become: yes
  become_method: sudo
  become_user: root
  vars:
   http_port: 80

  tasks:
  - name: Install Webserver
    yum: name=httpd state=latest

  - name: Start Webserver
    service: name=httpd state=started
    become: yes
    become_method: sudo
    become_user: root
